[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#163A36"
backgroundColor = "#E7EAEE"
secondaryBackgroundColor = "#F3F5F7"
textColor = "#15191E"
font = "sans serif"

[browser]
gatherUsageStats = false
